name: Deploy TUG Calendar Production
# on main branch updates
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          
      - name: Install dependencies
        run: npm ci
        env:
          HUSKY: 0

      - name: Get Google Project Config
        run: |
          echo '${{ secrets.TUG_GOOGLE_TOKEN }}' > ./tug-calendar-93d646f8c570.json
          
        #serverless deploy
      - name: Deploy with Serverless
        run: npx sls deploy -s production
        env:
          HUSKY: 0
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
